services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres-bd-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      PGDATA: /data/postgres
    networks:
      - bd-network
    volumes:
      - postgres-bd:/data/postgres
      - ../scripts/db-initializer.sh:/usr/local/bin/db-initializer.sh
    restart: unless-stopped


  config-ms:
    image: danilchet/config-ms
    container_name: config-ms-container
    ports:
      - "8888:8888"
    networks:
      - bd-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8888/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s


  patient-ms:
    image: danilchet/patient-ms
    container_name: patient-ms-container
    ports:
      - "4000:4000"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_CONFIG_URI=http://config-ms:8888
      - SPRING_CONFIG_IMPORT=configserver:http://config-ms:8888
    depends_on:
      - postgres
      - config-ms
    networks:
      - bd-network

  billing-ms:
    image: danilchet/billing-ms
    container_name: billing-ms-container
    ports:
      - "4001:4001"
      - "9001:9001"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_CONFIG_URI=http://config-ms:8888
      - SPRING_CONFIG_IMPORT=configserver:http://config-ms:8888
    depends_on:
      - config-ms
    networks:
      - bd-network


volumes:
  postgres-bd:

networks:
  bd-network:
    driver: bridge