services:
  config-ms:
    image: danilchet/config-ms
    container_name: config-ms-container
    ports:
      - "8888:8888"
    networks:
      - bd-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8888/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  gateway-ms:
    image: danilchet/gateway-ms
    container_name: gateway-ms-container
    ports:
      - "4003:4003"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:4003/actuator/health" ]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s
    networks:
      - bd-network

networks:
  bd-network:
    external: true