services:
  postgres-patient:
    image: postgres:16-alpine
    container_name: postgres-patient-bd-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      PGDATA: /data/postgres
    networks:
      - bd-network
    volumes:
      - postgres-bd:/data/postgres
      - ../scripts/db-initializer.sh:/usr/local/bin/db-initializer.sh
    restart: unless-stopped

  postgres-auth:
    image: postgres:16-alpine
    container_name: postgres-auth-bd-container
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      PGDATA: /data/postgres
    networks:
      - bd-network
    volumes:
      - postgres-bd-auth:/data/postgres
      - ../scripts/db-initializer.sh:/usr/local/bin/db-initializer.sh
    restart: unless-stopped

  kafka:
    image: bitnami/kafka
    container_name: kafka-bd-container
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
    networks:
      - bd-network

volumes:
  postgres-bd:
  postgres-bd-auth:

networks:
  bd-network:
    external: true
