spring:
  application:
    name: auth-ms
  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: true
  config:
    import: "configserver:"

jwt:
  secret: "U0FVLUJSQVQyMjgtaXQnc1N1cGVyJGVDcmVUS0tLS0tleQ=="
