spring:
  application:
    name: gateway-ms
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: patient-ms-route
              uri: http://patient-ms:4000
              predicates:
                - Path=/api/patients/**
              filters:
                - StripPrefix=1

            - id: patient-ms-api-docs-route
              uri: http://patient-ms:4000
              predicates:
                - Path=/patient/v3/**
              filters:
                - RewritePath=/patient/v3/(?<path>.*), /v3/$\{path}

            - id: patient-ms-swagger-route
              uri: http://patient-ms:4000
              predicates:
                - Path=/swagger/patients/**
              filters:
                - RewritePath=/swagger/patients/(?<path>.*), /swagger-ui/$\{path}

server:
  port: 4003