spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/patient_db
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always

logging:
  level:
    ru.pm.ex.patientms: WARN