spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/patient_db
    username: postgres
    password: root

  kafka:
    bootstrap-servers: kafka:9092

billing:
  service:
    address: billing-ms
    grps:
      port: 9091